# Numpy
1. Numpy 설치
  Numpy는 pip를 통해 쉽게 설치가 가능하다. <br>
  $ pip install numpy

In [42]:
# !pip install numpy

import numpy as np

# Numpy 배열 생성
numpy에서 가장 중요한 객체는 ndarray로 다차원 배열을 생성하고 관리할 수 있다.

1. list를 배열로 변환

In [43]:
arr = [1,2,3,4,5]
print(arr)
type(arr)

[1, 2, 3, 4, 5]


list

In [44]:
ndarry = np.array(arr)
print(ndarry)
type(ndarry)

[1 2 3 4 5]


numpy.ndarray

2. 다차원 배열

In [45]:
arr_2d = np.array([[1,2,3],[3,4,5]])
print(arr_2d)

[[1 2 3]
 [3 4 5]]


3. ndarray 배열의 속성
- 배열의 중요한 속성들을 확인하는 것은 배열의 구조를 파악하는데 필수적이다. <br>
  배열의 구조에 따라 데이터를 조작하는 방식이 달라지기 때문이다.

In [46]:
print(ndarry.shape) # 배열의 차원을 확인 - 1차원 5개
print(arr_2d.shape) #                   2차원 3개씩

print(ndarry.dtype) # 데이터의 타입을 확인
print(arr_2d.dtype) # 데이터의 타입을 확인

print(ndarry.ndim) # 배열의 차원 수 확인

(5,)
(2, 3)
int64
int64
1


4. 배열 초기화
- numpy는 배열을 초기화하는 여러 방법을 제공한다.

In [47]:
arr_2d = np.zeros([3,3]) # 3 * 3의 배열을 생성한다.
print(arr_2d)
print("---------------")

arr_2d = np.ones([2,2]) # 2 * 2 의 배열 생성, 값을 1로 채움
print(arr_2d)
print("---------------")

arr_2d = np.full([3,3] ,7) # 3 * 3 의 배열 생성, 값을 7로 채움
print(arr_2d)
print("---------------")

arr_2d = np.random.random([2,2]) # 2 * 2 의 랜덤 배열, 생성 값을 랜덤하게 채움
print(arr_2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------------
[[1. 1.]
 [1. 1.]]
---------------
[[7 7 7]
 [7 7 7]
 [7 7 7]]
---------------
[[0.24943277 0.39428092]
 [0.04653739 0.88562019]]


# 배열 연산 및 슬라이싱
- numpy는 벡터화된 연산을 지원, 배열 간의 연산을 매우 효율적으로 처리한다.

In [48]:
# list 간 덧셈
# 벡터 연산을 통해 두 배열의 같은 인덱스 위치에 값을 더한다.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [37]:
# 파이썬 리스트 간의 덧셈
# 두 배열을 합친다.

arr1 = [1, 2, 3]
arr2 = [4, 5, 6]

result = arr1 + arr2
print(result)

[1, 2, 3, 4, 5, 6]


In [40]:
# 배열 간 행렬 곱
result = arr1 * arr2 
print(result)

[ 4 10 18]


In [51]:
# 배열 간 행렬 곱
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

# 연산 과정
# 1*5 + 2*7 = 5, 14
# 1*6 + 2*8 = 6, 16
# 3*5 + 4*7 = 15, 28
# 3*6 + 4*8 = 16, 32

result = np.dot(arr1, arr2)
print(result)

[[19 22]
 [43 50]]


# 배열의 슬라이싱 및 인덱싱


In [53]:
# 1차원 배열 슬라이싱
arr = np.array([1,2,3,4,5])
print(arr[1:4]) # 1번째 - 4미만 인덱스

[2 3 4]


In [57]:
# 2차원 배열 슬라이싱
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_2d)
print(arr_2d[:2, 1:])

# 결과
# [[ :2 , 0 - 2까지 -> 행 지시
# ]] 1: , 1번 - 마지막 -> 열 지시

# 파이썬, R 사용 이유 : 연산 속도 차이, 데이터 전처리
# 배열을 통해 인덱싱하여 간단하게 사용 가능

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


# 배열의 형태 변경

In [61]:
arr = np.array([1,2,3,4,5,6]) 
reshaped_arr = arr.reshape((2,3)) # 2*3 배열로 변경 ( 1차원 -> 2차원 배열 )
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [62]:
# 조건 별 값 선택
arr = np.array([1,2,3,4,5])
condition = arr>3
list = [False,False,False, True, True]
filtered_arr = arr[condition]
print(filtered_arr)

[4 5]


# 고차원 배열 연산 및 고급 기능

In [63]:
# 고차원 배열
# numpy는 1차원 배열 뿐만 아니라 3차원, 4차원 이상의 고차원 배열도 쉽게 다룰 수 있다.
# r,g,b,g => 색의 조합 & g
arr_3d = np.random.random((3,3,3)) # 3*3*3 차원 배열 생성
print(arr_3d)

[[[0.47733792 0.93556893 0.29939553]
  [0.89906799 0.00853692 0.35554607]
  [0.6898391  0.70451427 0.1728162 ]]

 [[0.84504408 0.48049417 0.04696785]
  [0.26456446 0.29100075 0.2016618 ]
  [0.67562466 0.16945696 0.29791225]]

 [[0.51797398 0.98439937 0.71680647]
  [0.59362254 0.5644302  0.35123038]
  [0.36329907 0.09803086 0.65115952]]]


In [68]:
# 브로드 캐스팅
# 브로드 캐스팅은 서로 다른 크기의 배열 간의 연산을 가능하게 하는 강력한 기능
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([4,5,6])

result = arr1 + arr2
print(result)

# 연산 과정
# 1+4, 1+5, 1+6
# 2+4, 2+5, 2+6
# 3+4, 3+4, 3+6

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [69]:
# 고급 인덱싱 및 슬라이싱
# numpy는 불리언 배열과 정수 배열을 사용하여 복잡한 인덱싱을 지원
arr = np.array([10,20,30,40])
bool_arr = np.array([True, False, True, False])
filtered = arr[bool_arr]
print(filtered)

[10 30]


# 배열 합치기 및 나누기
- 배열을 수평 또는 수직으로 합치거나 나누는 방법

In [74]:
# 배열 합치기
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

# axis (0,1) 값을 가짐
# 0 - 행 기준
# 1 - 열 기준
concatenated = np.concatenate((arr1,arr2), axis=0)
print(concatenated)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [77]:
# 배열 나누기 -> 전처리 시 사용
arr = np.array([[1,2,3], [4,5,6]])

# split : 자르는 메서드
# axis (0,1)
# 0 행을 기준으로 자른다.
# 1 열을 기준으로 자른다.
split_arr = np.split(arr, 2, axis=0)
print(split_arr)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


# 고급 : Numpy 성능 최적화

In [78]:
# 벡터화 연산과 for 루프의 비교
arr = np.random.random(1000000) # 100만개의 난수 생성
# C언어 기반, 혼용 가능, 계산이 빠름 ( 고급 언어 )

# numpy sum, timeit ( 실행 시간 )
%timeit np.sum(arr)
# = arr.sum

# for 루프의 연산
def slow_sum(arr):
  total = 0
  for i in arr:
    total += i
  return total

%timeit slow_sum(arr)

1.12 ms ± 46.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
111 ms ± 4.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [80]:
# 메모리 관리 및 배열 복사
# numpy는 메모리를 활용해 효율적인 배열 복사 지원, 명시적으로 복사하지 않으면 같은 메모리 주소 공유

arr = np.array([1,2,3])
arr_copy = arr.copy()
print(arr_copy)

# 깊은 복사
list_copy = []
for x in arr:
  list_copy.append(x)

print(list_copy)

# 얕은 복사 ( 공유 객체 )
list_copy = arr

[1 2 3]
[np.int64(1), np.int64(2), np.int64(3)]


In [ ]:
# 고급 수학 함수
# NumPy는 선형 대수, 푸리에 변환, 통계 함수 등 고급 수학 함수들을 제공한다.

# 선형 대수
# 역행렬
# 정사각 행렬 𝐴A에 대해, 그 행렬과 곱했을 때 단위 행렬(identity matrix)을 만들어내는 행렬이다. 쉽게 말하면, 역행렬은 행렬을 "원래 상태로 돌려놓는" 역할을 하는 행렬이다.
arr = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(arr)  # 역행렬 구하기
print("역행렬 : ")
print(inverse)
print()

# 표준편차
mean = np.mean(arr)
std_dev = np.std(arr)
print("통계 함수 : ")
print(std_dev)